head	1.1;
access;
symbols;
locks; strict;
comment	@// @;


1.1
date	2011.03.14.02.31.55;	author che-jin;	state Exp;
branches;
next	;
deltatype	text;
kopt	kv;
permissions	666;
commitid	89c4d7d7dfd671c;
filename	DeleteAllTable.java;


desc
@@


1.1
log
@*** empty log message ***
@
text
@/**
Copyright        : (株)大和総研 証券ソリューションシステム第二部
File Name        : 
Author Name      : Daiwa Institute of Research
Revesion History : 
*/
package test.util;

import webbroker3.accountinfo.data.CommAccountSendRow;
import webbroker3.accountinfo.data.CommCampaignAccHistoryRow;
import webbroker3.accountinfo.data.CommCampaignCondMstRow;
import webbroker3.accountinfo.data.CommCampaignProductMstRow;
import webbroker3.accountinfo.data.CommissionCourseMasterRow;
import webbroker3.accountinfo.data.CommissionCourseRegistRow;
import webbroker3.accountinfo.data.HostLockRegiAcceptRow;
import webbroker3.accountinfo.data.HostLockRegistRow;
import webbroker3.accountinfo.data.InformationMailRequestRow;
import webbroker3.accountinfo.data.MobileOfficeInfoRegistRow;
import webbroker3.accountopen.data.AccOpenAccountCodeRow;
import webbroker3.accountopen.data.AccOpenDlFormMasterRow;
import webbroker3.accountopen.data.AccOpenInvalidValuesRow;
import webbroker3.accountopen.data.AccOpenItemAttributeRow;
import webbroker3.accountopen.data.AccOpenItemMasterRow;
import webbroker3.accountopen.data.AccOpenRequestNumberRow;
import webbroker3.accountopen.data.AccOpenVoucherItemRow;
import webbroker3.accountopen.data.AccOpenVoucherMasterRow;
import webbroker3.accountopen.data.AccOpenVoucherStatusRow;
import webbroker3.accountopen.data.AccOpenWaitingRow;
import webbroker3.accountopen.data.BatchBranchRow;
import webbroker3.accountopen.data.BatchPreferencesRow;
import webbroker3.accountopen.data.ExpAccountOpenRow;
import webbroker3.accountopen.data.HostAccOpenAcceptRow;
import webbroker3.accountopen.data.HostAccRegVoucherRow;
import webbroker3.accountopen.data.HostAgreeTransVoucherRow;
import webbroker3.accountopen.data.HostBankTransVoucherRow;
import webbroker3.accountopen.data.HostChargedInfoVoucherRow;
import webbroker3.accountopen.data.HostConditionRegVoucherRow;
import webbroker3.accountopen.data.HostContMrgVoucherRow;
import webbroker3.accountopen.data.HostFDepositVoucherRow;
import webbroker3.accountopen.data.HostGpRegVoucherRow;
import webbroker3.accountopen.data.HostInsiderRegVoucherRow;
import webbroker3.accountopen.data.HostMrfAccVoucherRow;
import webbroker3.accountopen.data.HostPostalTransVoucherRow;
import webbroker3.accountopen.data.HostRealnameRegVoucherRow;
import webbroker3.accountopen.data.HostStockholderRegVoucherRow;
import webbroker3.accountopen.data.IdConfirmVoucherRow;
import webbroker3.accountopen.data.ImpConfirmVoucherRow;
import webbroker3.accountopen.data.PasswordVoucherRow;
import webbroker3.accountopen.data.TradeConditionVoucherRow;
import webbroker3.accountopen.data.YCustomerRow;
import webbroker3.aio.data.AioDepositInformSendMailRow;
import webbroker3.aio.data.AmountRangeRow;
import webbroker3.aio.data.BankCashTransferStatusRow;
import webbroker3.aio.data.BankDepositErrorHistoryRow;
import webbroker3.aio.data.BankDepositNotifyRow;
import webbroker3.aio.data.BankOrderRequestRow;
import webbroker3.aio.data.BankSettleResultResponseRow;
import webbroker3.aio.data.BankSettleStartRequestRow;
import webbroker3.aio.data.CareerShopIdRow;
import webbroker3.aio.data.CompBankCareerManagementRow;
import webbroker3.aio.data.CompBankConditionRow;
import webbroker3.aio.data.CompFxConditionRow;
import webbroker3.aio.data.CooperateBankMasterRow;
import webbroker3.aio.data.DepositInformRow;
import webbroker3.aio.data.FeqAccountRow;
import webbroker3.aio.data.FxAccountCodeRow;
import webbroker3.aio.data.FxAccountRow;
import webbroker3.aio.data.FxUnnecessaryExplanationRow;
import webbroker3.aio.data.GftAccountOpenStatusRow;
import webbroker3.aio.data.GftMessageRow;
import webbroker3.aio.data.GftTransferStatusRow;
import webbroker3.aio.data.HostCashTransOrderAcceptRow;
import webbroker3.aio.data.HostCashTransOrderRow;
import webbroker3.aio.data.HostCashTransferRow;
import webbroker3.aio.data.HostFCashTransOrderAcceptRow;
import webbroker3.aio.data.HostForeignCashTransOrderRow;
import webbroker3.aio.data.HostForeignCashTransferRow;
import webbroker3.aio.data.HostMrgsecTransAcceptRow;
import webbroker3.aio.data.HostMrgsecTransNotifyRow;
import webbroker3.aio.data.HostMrgsecTransferRow;
import webbroker3.aio.data.HostPaymentAcceptRow;
import webbroker3.aio.data.HostPaymentOrderRow;
import webbroker3.aio.data.HostSecDeliveryTransferRow;
import webbroker3.aio.data.HostSpsecTransNotifyRow;
import webbroker3.aio.data.HostTransferAcceptRow;
import webbroker3.aio.data.HostTransferOrderRow;
import webbroker3.aio.data.HostTransferPaymentRow;
import webbroker3.aio.data.HostTransferReceiptRow;
import webbroker3.aio.data.OtherOrderExecutedCountRow;
import webbroker3.aio.data.PayRequiredAmountRow;
import webbroker3.aio.data.SecReceiptDeliveryActionRow;
import webbroker3.aio.data.SecurityProductRow;
import webbroker3.aio.data.SsoMessageRow;
import webbroker3.aio.data.UwgAccountOpenStatusRow;
import webbroker3.aio.data.UwgTransferStatusRow;
import webbroker3.bd.data.AccruedInterestCalcCondRow;
import webbroker3.bd.data.BondAutoExecLimitActionRow;
import webbroker3.bd.data.BondBranchConditionRow;
import webbroker3.bd.data.BondProductCouponRow;
import webbroker3.bd.data.CustodianRow;
import webbroker3.common.WEB3BaseException;
import webbroker3.equity.data.EqtypeOrderExecSendMailRow;
import webbroker3.equity.data.EquityLimitPriceRangeMstRow;
import webbroker3.equity.data.EquityTickValuesMstRow;
import webbroker3.equity.data.HostEqtypeCloseOrderNotifyRow;
import webbroker3.equity.data.HostEqtypeOrderAcceptRow;
import webbroker3.equity.data.HostEqtypeOrderAllRow;
import webbroker3.equity.data.HostEqtypeOrderClmdReceiptRow;
import webbroker3.equity.data.HostEqtypeOrderHistoryRow;
import webbroker3.equity.data.HostEqtypeOrderReceiptRow;
import webbroker3.equity.data.HostEqtypeSwapAcceptRow;
import webbroker3.equity.data.HostEqtypeSwapReceiptRow;
import webbroker3.equity.data.HostEqtypeSwapRow;
import webbroker3.equity.data.HostEquityCarryoverSkipRow;
import webbroker3.equity.data.HostEquityOrderExecNotifyRow;
import webbroker3.equity.data.MarketNoticeManagementRow;
import webbroker3.equity.data.OffFloorOrderProductRow;
import webbroker3.equity.data.OrderCarryoverSkipProdRow;
import webbroker3.equity.data.ShortSellingRestraintTimeRow;
import webbroker3.faq.data.FaqNumberRow;
import webbroker3.faq.data.FaqRow;
import webbroker3.feq.data.FCashBalanceRow;
import webbroker3.feq.data.FeqLimitPriceRangeMstRow;
import webbroker3.feq.data.FeqOrderChangeStatusRow;
import webbroker3.feq.data.FeqOrderEmpNumberRow;
import webbroker3.feq.data.FeqOrderexecutionEndRow;
import webbroker3.feq.data.FeqTickValuesMstRow;
import webbroker3.feq.data.ForeignCostRow;
import webbroker3.feq.data.HostFeqChangecancelOrderRow;
import webbroker3.feq.data.HostFeqCloseOrderNotifyRow;
import webbroker3.feq.data.HostFeqOrderAcceptRow;
import webbroker3.feq.data.HostFeqOrderExecNotifyRow;
import webbroker3.feq.data.HostFeqOrderRow;
import webbroker3.gentrade.data.AccountInfoMstRow;
import webbroker3.gentrade.data.AccountProductOrderStopRow;
import webbroker3.gentrade.data.AccountTransferRow;
import webbroker3.gentrade.data.AdminPermissionRow;
import webbroker3.gentrade.data.AdministratorRow;
import webbroker3.gentrade.data.AdministratorTypeRow;
import webbroker3.gentrade.data.AdministratorUploadRow;
import webbroker3.gentrade.data.AdministratorUploadTempRow;
import webbroker3.gentrade.data.BatoBranchProductPrefRow;
import webbroker3.gentrade.data.BatoDoctypeManagementRow;
import webbroker3.gentrade.data.BatoFunctionPrefRow;
import webbroker3.gentrade.data.BatoInstBranchPrefRow;
import webbroker3.gentrade.data.BatoProductManagementRow;
import webbroker3.gentrade.data.BranchIndexDealtCondRow;
import webbroker3.gentrade.data.BranchListmarketDealtCondRow;
import webbroker3.gentrade.data.BranchMarketDealtCondRow;
import webbroker3.gentrade.data.BranchMarketPtsDealtCondRow;
import webbroker3.gentrade.data.BranchMarketRepayDealtCondRow;
import webbroker3.gentrade.data.BranchPreferencesRow;
import webbroker3.gentrade.data.CalendarRow;
import webbroker3.gentrade.data.CodeTranslationRow;
import webbroker3.gentrade.data.CommCodeChgMstRow;
import webbroker3.gentrade.data.CommSerialNumbersRow;
import webbroker3.gentrade.data.DaemonTriggerRow;
import webbroker3.gentrade.data.DailyAssetRow;
import webbroker3.gentrade.data.DirectDebitRow;
import webbroker3.gentrade.data.DocCategoryManagementRow;
import webbroker3.gentrade.data.DocDeliveryManagementHistRow;
import webbroker3.gentrade.data.DocDeliveryManagementRow;
import webbroker3.gentrade.data.DocDivManagementRow;
import webbroker3.gentrade.data.EnableOrderConditionRow;
import webbroker3.gentrade.data.EquityCommAccountCondMstRow;
import webbroker3.gentrade.data.EquityCommCondMstRow;
import webbroker3.gentrade.data.EquityCommCondRow;
import webbroker3.gentrade.data.EquityCommRevMstRow;
import webbroker3.gentrade.data.ExchangeRateRow;
import webbroker3.gentrade.data.ExclusiveUseAccountCondRow;
import webbroker3.gentrade.data.ExclusiveUseAccountRow;
import webbroker3.gentrade.data.ExtMailProcRow;
import webbroker3.gentrade.data.ExtMailProcTempRow;
import webbroker3.gentrade.data.FTransFinInstitutionRow;
import webbroker3.gentrade.data.FeqBranchMarketDealtCondRow;
import webbroker3.gentrade.data.FeqCalendarRow;
import webbroker3.gentrade.data.FeqLastClosingPriceRow;
import webbroker3.gentrade.data.FinInstitutionAvailableRow;
import webbroker3.gentrade.data.FinInstitutionBankRow;
import webbroker3.gentrade.data.FinInstitutionRow;
import webbroker3.gentrade.data.FrgnMmfExchangeRateRow;
import webbroker3.gentrade.data.GenCurrencyRow;
import webbroker3.gentrade.data.HostOrderexecutionEndRow;
import webbroker3.gentrade.data.HostRequestOrderNumberRow;
import webbroker3.gentrade.data.IfoDepositRow;
import webbroker3.gentrade.data.InsiderRow;
import webbroker3.gentrade.data.InstBranchProductRow;
import webbroker3.gentrade.data.LastClosingPriceRow;
import webbroker3.gentrade.data.LoginHistoryPastRow;
import webbroker3.gentrade.data.LoginHistoryRow;
import webbroker3.gentrade.data.LoginRejectIpRow;
import webbroker3.gentrade.data.LoginWdogAttributeRow;
import webbroker3.gentrade.data.MailInfoRow;
import webbroker3.gentrade.data.MailProcRow;
import webbroker3.gentrade.data.MailProcTempRow;
import webbroker3.gentrade.data.MainAccountAllRow;
import webbroker3.gentrade.data.MarketMarginRatioRow;
import webbroker3.gentrade.data.OnlineRunStatusRow;
import webbroker3.gentrade.data.OrderAcceptStatusRow;
import webbroker3.gentrade.data.OrderSwitchingRow;
import webbroker3.gentrade.data.OrderUnitIntroduceDivRow;
import webbroker3.gentrade.data.OrderexecutionEndRow;
import webbroker3.gentrade.data.OtherOrgOutOfSrvDateRow;
import webbroker3.gentrade.data.OtherOrgOutOfSrvWeekRow;
import webbroker3.gentrade.data.OtherOrgSrvTimeRow;
import webbroker3.gentrade.data.ProcessManagementRow;
import webbroker3.gentrade.data.ProductEstimationRatioRow;
import webbroker3.gentrade.data.PtsOrderexecutionEndRow;
import webbroker3.gentrade.data.QuestionAnswerRow;
import webbroker3.gentrade.data.QuestionRow;
import webbroker3.gentrade.data.QuoteClosingPriceRow;
import webbroker3.gentrade.data.RequestCodesForReadRow;
import webbroker3.gentrade.data.SecurityCashoutRestraintRow;
import webbroker3.gentrade.data.SecurityShortageAccountHistRow;
import webbroker3.gentrade.data.SecurityShortageAccountRow;
import webbroker3.gentrade.data.SoapConnectPrefMsgRow;
import webbroker3.gentrade.data.SoapConnectPrefRpcRow;
import webbroker3.gentrade.data.SoapMessageRow;
import webbroker3.gentrade.data.SonarTraderRow;
import webbroker3.gentrade.data.SrvRegiApplicationRow;
import webbroker3.gentrade.data.StockOptionProductRow;
import webbroker3.gentrade.data.StockSecuredLoanRow;
import webbroker3.gentrade.data.TaxRateTableRow;
import webbroker3.gentrade.data.TraderAccountInfoRow;
import webbroker3.gentrade.data.TradingTimeRow;
import webbroker3.gentrade.data.TradingpowerCalcConditionRow;
import webbroker3.gentrade.data.TransferedFinInstitutionRow;
import webbroker3.gentrade.data.VirtualServerChangeRow;
import webbroker3.gentrade.data.VirtualServerInformationRow;
import webbroker3.gentrade.data.YellowCustomerRow;
import webbroker3.ifo.data.HostFotypeCloseOrderNotifyRow;
import webbroker3.ifo.data.HostFotypeClosingContSpecRow;
import webbroker3.ifo.data.HostFotypeOrderAcceptRow;
import webbroker3.ifo.data.HostFotypeOrderAllRow;
import webbroker3.ifo.data.HostFotypeOrderClmdNotifyRow;
import webbroker3.ifo.data.HostFotypeOrderHistoryRow;
import webbroker3.ifo.data.HostFotypeOrderReceiptRow;
import webbroker3.ifo.data.HostOptionOrderExecNotifyRow;
import webbroker3.ifo.data.IfoIndexMasterRow;
import webbroker3.ifo.data.IfoLimitPriceRangeMasterRow;
import webbroker3.ifo.data.IfoOrderCarryoverSkipProdRow;
import webbroker3.ifo.data.IfoOrderExecSendMailRow;
import webbroker3.ifo.data.IfoTickValuesMasterRow;
import webbroker3.inform.data.InformCtrlItemAttributeRow;
import webbroker3.inform.data.InformCtrlItemMasterRow;
import webbroker3.inform.data.InformCtrlRequestNumberRow;
import webbroker3.inform.data.InformDivPreferencesRow;
import webbroker3.inform.data.InformDlFormMasterRow;
import webbroker3.inform.data.VariousInformRow;
import webbroker3.ipo.data.IpoBookbuildingOrderActionRow;
import webbroker3.ipo.data.IpoBookbuildingRow;
import webbroker3.ipo.data.IpoOrderRow;
import webbroker3.ipo.data.IpoProductRow;
import webbroker3.mf.data.HostFrgnMmfOrderAcceptRow;
import webbroker3.mf.data.HostFrgnMmfOrderRow;
import webbroker3.mf.data.HostXbmfCancelAcceptRow;
import webbroker3.mf.data.HostXbmfOrderAcceptRow;
import webbroker3.mf.data.HostXbmfOrderCancelRow;
import webbroker3.mf.data.HostXbmfOrderNotifyRow;
import webbroker3.mf.data.HostXbmfOrderRow;
import webbroker3.mf.data.MfExemptionAccountRow;
import webbroker3.mf.data.MfFixedBuyingCondRow;
import webbroker3.mf.data.MfFixedBuyingDrawAccountRow;
import webbroker3.mf.data.MfSubAssetRow;
import webbroker3.mf.data.MutualFundDayBalanceRow;
import webbroker3.mf.data.MutualFundExchangeRateRow;
import webbroker3.mf.data.MutualFundFrgncalRow;
import webbroker3.mf.data.MutualFundInstCommissionRow;
import webbroker3.mf.data.MutualFundInstCondSonarRow;
import webbroker3.mf.data.MutualFundProductCategoryRow;
import webbroker3.mf.data.MutualFundProductSonarRow;
import webbroker3.mock.TestBaseForMock;
import webbroker3.mqgateway.stdimpls.data.MqMessageIdMappingsRow;
import webbroker3.point.data.OrixTradeBonusPlanRow;
import webbroker3.point.data.PointAdjustRow;
import webbroker3.point.data.PointApplyRow;
import webbroker3.point.data.PointCategoryMasterRow;
import webbroker3.point.data.PointConvertMasterRow;
import webbroker3.point.data.PointPremiumMasterRow;
import webbroker3.point.data.PointTermRow;
import webbroker3.point.data.PointTotalRow;
import webbroker3.point.data.PointTradeDataRow;
import webbroker3.quoteadaptor.prototype.data.Web3QuoteProtoRow;
import webbroker3.rlsgateway.data.OmsConOrderRequestRow;
import webbroker3.rlsgateway.data.RlsAccountRow;
import webbroker3.rlsgateway.data.RlsConOrderHitNotifyRow;
import webbroker3.rlsgateway.data.RlsCondOrderRow;
import webbroker3.rlsgateway.data.RlsManualSubmitHistoryRow;
import webbroker3.rlsgateway.data.RlsOmsOrderRow;
import webbroker3.rlsgateway.data.RlsOrderMissRow;
import webbroker3.rlsgateway.data.RlsPriceCondRow;
import webbroker3.tradingpower.data.EqtypeFixedContractRow;
import webbroker3.tradingpower.data.FixedFinTransactionRow;
import webbroker3.tradingpower.data.OrixTpCalcResultEquityRow;
import webbroker3.tradingpower.data.OrixTpCalcResultMarginRow;
import webbroker3.tradingpower.data.PaymentRequisitMngRow;
import webbroker3.tradingpower.data.TpAssetHistoryRow;
import webbroker3.tradingpower.data.TpCalcResultEquityDetailRow;
import webbroker3.tradingpower.data.TpCalcResultEquityRow;
import webbroker3.tradingpower.data.TpCalcResultExecNotifyRow;
import webbroker3.tradingpower.data.TpCalcResultMarginDetailRow;
import webbroker3.tradingpower.data.TpCalcResultMarginRow;
import webbroker3.tradingpower.data.TpCashBalanceFrgnRow;
import webbroker3.tradingpower.data.TpCashBalanceRow;
import webbroker3.tradingpower.data.TpOtherTempRestraintRow;
import webbroker3.trialcalc.data.AccountPortfolioProductRow;
import webbroker3.trialcalc.data.AccountPortfolioRow;
import webbroker3.triggerorder.base.data.RsvEqClosingContractSpecRow;
import webbroker3.triggerorder.base.data.RsvEqOrderActionRow;
import webbroker3.triggerorder.base.data.RsvEqOrderUnitRow;
import webbroker3.triggerorder.base.data.RsvIfoClosingContractSpecRow;
import webbroker3.triggerorder.base.data.RsvIfoOrderActionRow;
import webbroker3.triggerorder.base.data.RsvIfoOrderUnitRow;
import webbroker3.triggerorder.base.data.TriggerOrderStopRow;
import webbroker3.xbruito.data.HostMrfCancelAcceptRow;
import webbroker3.xbruito.data.HostMrfOrderAcceptRow;
import webbroker3.xbruito.data.HostMrfOrderCancelRow;
import webbroker3.xbruito.data.HostMrfOrderRow;
import webbroker3.xbruito.data.HostRuitoCancelAcceptRow;
import webbroker3.xbruito.data.HostRuitoOrderAcceptRow;
import webbroker3.xbruito.data.HostRuitoOrderCancelRow;
import webbroker3.xbruito.data.HostRuitoOrderNotifyRow;
import webbroker3.xbruito.data.HostRuitoOrderRow;
import webbroker3.xbruito.data.HostRuitoSellRow;
import webbroker3.xbruito.data.HostSellCancelRow;

import com.fitechlabs.xtrade.kernel.data.db.AccountSegmentRow;
import com.fitechlabs.xtrade.kernel.data.db.SegmentUrlRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginAccountManagerRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginAccountRelationRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginAttributeRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginGroupManagerRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginGroupMemberRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginGroupRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginLoginManagerRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginLoginRelationRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginPermissionRuleRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginSessionPropertyRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginSessionRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginTypeAttributeRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginTypeRow;
import com.fitechlabs.xtrade.plugin.security.oplogin.data.LoginUsernameRow;
import com.fitechlabs.xtrade.plugin.tc.eqtype.data.EqtypeClosingContractSpecRow;
import com.fitechlabs.xtrade.plugin.tc.eqtype.data.EqtypeContractRow;
import com.fitechlabs.xtrade.plugin.tc.eqtype.data.EqtypeFinTransactionRow;
import com.fitechlabs.xtrade.plugin.tc.eqtype.data.EqtypeLockedContractDetailsRow;
import com.fitechlabs.xtrade.plugin.tc.eqtype.data.EqtypeOrderActionRow;
import com.fitechlabs.xtrade.plugin.tc.eqtype.data.EqtypeOrderExecutionRow;
import com.fitechlabs.xtrade.plugin.tc.eqtype.data.EqtypeOrderRow;
import com.fitechlabs.xtrade.plugin.tc.eqtype.data.EqtypeOrderUnitRow;
import com.fitechlabs.xtrade.plugin.tc.eqtype.data.EqtypeProductRow;
import com.fitechlabs.xtrade.plugin.tc.eqtype.data.EqtypeTradedProductRow;
import com.fitechlabs.xtrade.plugin.tc.eqtype.data.EqtypeTradedProductUpdqRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.AccountPreferencesRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.AssetRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.AssetUnitRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.AssetUnitSalesRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.BranchRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.GenFinTransactionRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.InstitutionRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.LimitPriceRangeDefsRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.LockedAssetDetailsRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.MainAccountRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.MarketCalendarRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.MarketPreferencesRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.MarketRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.ParticipantRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.ProductRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.SubAccountPreferencesRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.SubAccountRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.SystemPreferencesRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.TickValuesDefsRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.TradedProductCalendarRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.TradedProductRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.TradedProductUpdqRow;
import com.fitechlabs.xtrade.plugin.tc.gentrade.data.TraderRow;
import com.fitechlabs.xtrade.plugin.tc.xbaio.data.AioFinTransactionRow;
import com.fitechlabs.xtrade.plugin.tc.xbaio.data.AioOrderActionRow;
import com.fitechlabs.xtrade.plugin.tc.xbaio.data.AioOrderRow;
import com.fitechlabs.xtrade.plugin.tc.xbaio.data.AioOrderUnitRow;
import com.fitechlabs.xtrade.plugin.tc.xbbd.data.BondFinTransactionRow;
import com.fitechlabs.xtrade.plugin.tc.xbbd.data.BondOrderActionRow;
import com.fitechlabs.xtrade.plugin.tc.xbbd.data.BondOrderExecutionRow;
import com.fitechlabs.xtrade.plugin.tc.xbbd.data.BondOrderRow;
import com.fitechlabs.xtrade.plugin.tc.xbbd.data.BondOrderUnitRow;
import com.fitechlabs.xtrade.plugin.tc.xbbd.data.BondProductRow;
import com.fitechlabs.xtrade.plugin.tc.xbbd.data.BondTradedProductRow;
import com.fitechlabs.xtrade.plugin.tc.xbbd.data.BondTradedProductUpdqRow;
import com.fitechlabs.xtrade.plugin.tc.xbfeq.data.FeqFinTransactionRow;
import com.fitechlabs.xtrade.plugin.tc.xbfeq.data.FeqOrderActionRow;
import com.fitechlabs.xtrade.plugin.tc.xbfeq.data.FeqOrderExecutionRow;
import com.fitechlabs.xtrade.plugin.tc.xbfeq.data.FeqOrderRow;
import com.fitechlabs.xtrade.plugin.tc.xbfeq.data.FeqOrderUnitRow;
import com.fitechlabs.xtrade.plugin.tc.xbfeq.data.FeqProductRow;
import com.fitechlabs.xtrade.plugin.tc.xbfeq.data.FeqTradedProductRow;
import com.fitechlabs.xtrade.plugin.tc.xbfeq.data.FeqTradedProductUpdqRow;
import com.fitechlabs.xtrade.plugin.tc.xbifo.data.IfoClosingContractSpecRow;
import com.fitechlabs.xtrade.plugin.tc.xbifo.data.IfoContractRow;
import com.fitechlabs.xtrade.plugin.tc.xbifo.data.IfoFinTransactionRow;
import com.fitechlabs.xtrade.plugin.tc.xbifo.data.IfoLockedContractDetailsRow;
import com.fitechlabs.xtrade.plugin.tc.xbifo.data.IfoOrderActionRow;
import com.fitechlabs.xtrade.plugin.tc.xbifo.data.IfoOrderExecutionRow;
import com.fitechlabs.xtrade.plugin.tc.xbifo.data.IfoOrderRow;
import com.fitechlabs.xtrade.plugin.tc.xbifo.data.IfoOrderUnitRow;
import com.fitechlabs.xtrade.plugin.tc.xbifo.data.IfoProductRow;
import com.fitechlabs.xtrade.plugin.tc.xbifo.data.IfoTradedProductRow;
import com.fitechlabs.xtrade.plugin.tc.xbifo.data.IfoTradedProductUpdqRow;
import com.fitechlabs.xtrade.plugin.tc.xbmf.data.MfTradedProductUpdqRow;
import com.fitechlabs.xtrade.plugin.tc.xbmf.data.MutualFundFinTransactionRow;
import com.fitechlabs.xtrade.plugin.tc.xbmf.data.MutualFundOrderActionRow;
import com.fitechlabs.xtrade.plugin.tc.xbmf.data.MutualFundOrderExecutionRow;
import com.fitechlabs.xtrade.plugin.tc.xbmf.data.MutualFundOrderRow;
import com.fitechlabs.xtrade.plugin.tc.xbmf.data.MutualFundOrderUnitRow;
import com.fitechlabs.xtrade.plugin.tc.xbmf.data.MutualFundProductRow;
import com.fitechlabs.xtrade.plugin.tc.xbmf.data.MutualFundTradedProductRow;
import com.fitechlabs.xtrade.plugin.tc.xbruito.data.RuitoFinTransactionRow;
import com.fitechlabs.xtrade.plugin.tc.xbruito.data.RuitoOrderActionRow;
import com.fitechlabs.xtrade.plugin.tc.xbruito.data.RuitoOrderExecutionRow;
import com.fitechlabs.xtrade.plugin.tc.xbruito.data.RuitoOrderRow;
import com.fitechlabs.xtrade.plugin.tc.xbruito.data.RuitoOrderUnitRow;
import com.fitechlabs.xtrade.plugin.tc.xbruito.data.RuitoProductRow;
import com.fitechlabs.xtrade.plugin.tc.xbruito.data.RuitoTradedProductRow;
import com.fitechlabs.xtrade.plugin.tc.xbruito.data.RuitoTradedProductUpdqRow;

public class DeleteAllTable extends TestBaseForMock
{

    public DeleteAllTable(String name)
    {
        super(name);
    }

    public void test_init() throws WEB3BaseException
    {
        TestDBUtility.deleteAll(AccountInfoMstRow.TYPE);
        TestDBUtility.deleteAll(AccountPortfolioRow.TYPE);
        TestDBUtility.deleteAll(AccountPortfolioProductRow.TYPE);
        TestDBUtility.deleteAll(AccountPreferencesRow.TYPE);
        TestDBUtility.deleteAll(AccountProductOrderStopRow.TYPE);
        TestDBUtility.deleteAll(AccountSegmentRow.TYPE);
        TestDBUtility.deleteAll(AccountTransferRow.TYPE);
        TestDBUtility.deleteAll(AccruedInterestCalcCondRow.TYPE);
        TestDBUtility.deleteAll(AccOpenAccountCodeRow.TYPE);
        TestDBUtility.deleteAll(AccOpenDlFormMasterRow.TYPE);
        TestDBUtility.deleteAll(AccOpenInvalidValuesRow.TYPE);
        TestDBUtility.deleteAll(AccOpenItemAttributeRow.TYPE);
        TestDBUtility.deleteAll(AccOpenItemMasterRow.TYPE);
        TestDBUtility.deleteAll(AccOpenRequestNumberRow.TYPE);
        TestDBUtility.deleteAll(AccOpenVoucherItemRow.TYPE);
        TestDBUtility.deleteAll(AccOpenVoucherMasterRow.TYPE);
        TestDBUtility.deleteAll(AccOpenVoucherStatusRow.TYPE);
        TestDBUtility.deleteAll(AccOpenWaitingRow.TYPE);
        TestDBUtility.deleteAll(AdministratorRow.TYPE);
        TestDBUtility.deleteAll(AdministratorTypeRow.TYPE);
        TestDBUtility.deleteAll(AdministratorUploadRow.TYPE);
        TestDBUtility.deleteAll(AdministratorUploadTempRow.TYPE);
        TestDBUtility.deleteAll(AdminPermissionRow.TYPE);
        TestDBUtility.deleteAll(AioDepositInformSendMailRow.TYPE);
        TestDBUtility.deleteAll(AioFinTransactionRow.TYPE);
        TestDBUtility.deleteAll(AioOrderRow.TYPE);
        TestDBUtility.deleteAll(AioOrderActionRow.TYPE);
        TestDBUtility.deleteAll(AioOrderUnitRow.TYPE);
        TestDBUtility.deleteAll(AmountRangeRow.TYPE);
        TestDBUtility.deleteAll(AssetRow.TYPE);
        TestDBUtility.deleteAll(AssetUnitRow.TYPE);
        TestDBUtility.deleteAll(AssetUnitSalesRow.TYPE);
        TestDBUtility.deleteAll(BankCashTransferStatusRow.TYPE);
        TestDBUtility.deleteAll(BankDepositErrorHistoryRow.TYPE);
        TestDBUtility.deleteAll(BankDepositNotifyRow.TYPE);
        TestDBUtility.deleteAll(BankOrderRequestRow.TYPE);
        TestDBUtility.deleteAll(BankSettleResultResponseRow.TYPE);
        TestDBUtility.deleteAll(BankSettleStartRequestRow.TYPE);
        TestDBUtility.deleteAll(BatchBranchRow.TYPE);
        TestDBUtility.deleteAll(BatchPreferencesRow.TYPE);
        TestDBUtility.deleteAll(BatoBranchProductPrefRow.TYPE);
        TestDBUtility.deleteAll(BatoDoctypeManagementRow.TYPE);
        TestDBUtility.deleteAll(BatoFunctionPrefRow.TYPE);
        TestDBUtility.deleteAll(BatoInstBranchPrefRow.TYPE);
        TestDBUtility.deleteAll(BatoProductManagementRow.TYPE);
        TestDBUtility.deleteAll(BondAutoExecLimitActionRow.TYPE);
        TestDBUtility.deleteAll(BondBranchConditionRow.TYPE);
        TestDBUtility.deleteAll(BondFinTransactionRow.TYPE);
        TestDBUtility.deleteAll(BondOrderRow.TYPE);
        TestDBUtility.deleteAll(BondOrderActionRow.TYPE);
        TestDBUtility.deleteAll(BondOrderExecutionRow.TYPE);
        TestDBUtility.deleteAll(BondOrderUnitRow.TYPE);
        TestDBUtility.deleteAll(BondProductRow.TYPE);
        TestDBUtility.deleteAll(BondProductCouponRow.TYPE);
        TestDBUtility.deleteAll(BondTradedProductRow.TYPE);
        TestDBUtility.deleteAll(BondTradedProductUpdqRow.TYPE);
        TestDBUtility.deleteAll(BranchRow.TYPE);
        TestDBUtility.deleteAll(BranchIndexDealtCondRow.TYPE);
        TestDBUtility.deleteAll(BranchListmarketDealtCondRow.TYPE);
        TestDBUtility.deleteAll(BranchMarketDealtCondRow.TYPE);
        TestDBUtility.deleteAll(BranchMarketPtsDealtCondRow.TYPE);
        TestDBUtility.deleteAll(BranchMarketRepayDealtCondRow.TYPE);
        TestDBUtility.deleteAll(BranchPreferencesRow.TYPE);
        TestDBUtility.deleteAll(CalendarRow.TYPE);
        TestDBUtility.deleteAll(CareerShopIdRow.TYPE);
        TestDBUtility.deleteAll(CodeTranslationRow.TYPE);
        TestDBUtility.deleteAll(CommissionCourseMasterRow.TYPE);
        TestDBUtility.deleteAll(CommissionCourseRegistRow.TYPE);
        TestDBUtility.deleteAll(CommAccountSendRow.TYPE);
        TestDBUtility.deleteAll(CommCampaignAccHistoryRow.TYPE);
        TestDBUtility.deleteAll(CommCampaignCondMstRow.TYPE);
        TestDBUtility.deleteAll(CommCampaignProductMstRow.TYPE);
        TestDBUtility.deleteAll(CommCodeChgMstRow.TYPE);
        TestDBUtility.deleteAll(CommSerialNumbersRow.TYPE);
        TestDBUtility.deleteAll(CompBankCareerManagementRow.TYPE);
        TestDBUtility.deleteAll(CompBankConditionRow.TYPE);
        TestDBUtility.deleteAll(CompFxConditionRow.TYPE);
        TestDBUtility.deleteAll(CooperateBankMasterRow.TYPE);
        TestDBUtility.deleteAll(CustodianRow.TYPE);
        TestDBUtility.deleteAll(DaemonTriggerRow.TYPE);
        TestDBUtility.deleteAll(DailyAssetRow.TYPE);
        TestDBUtility.deleteAll(DepositInformRow.TYPE);
        TestDBUtility.deleteAll(DirectDebitRow.TYPE);
        TestDBUtility.deleteAll(DocCategoryManagementRow.TYPE);
        TestDBUtility.deleteAll(DocDeliveryManagementRow.TYPE);
        TestDBUtility.deleteAll(DocDeliveryManagementHistRow.TYPE);
        TestDBUtility.deleteAll(DocDivManagementRow.TYPE);
        TestDBUtility.deleteAll(EnableOrderConditionRow.TYPE);
        TestDBUtility.deleteAll(EqtypeClosingContractSpecRow.TYPE);
        TestDBUtility.deleteAll(EqtypeContractRow.TYPE);
        TestDBUtility.deleteAll(EqtypeFinTransactionRow.TYPE);
        TestDBUtility.deleteAll(EqtypeFixedContractRow.TYPE);
        TestDBUtility.deleteAll(EqtypeLockedContractDetailsRow.TYPE);
        TestDBUtility.deleteAll(EqtypeOrderRow.TYPE);
        TestDBUtility.deleteAll(EqtypeOrderActionRow.TYPE);
        TestDBUtility.deleteAll(EqtypeOrderExecutionRow.TYPE);
        TestDBUtility.deleteAll(EqtypeOrderExecSendMailRow.TYPE);
        TestDBUtility.deleteAll(EqtypeOrderUnitRow.TYPE);
        TestDBUtility.deleteAll(EqtypeProductRow.TYPE);
        TestDBUtility.deleteAll(EqtypeTradedProductRow.TYPE);
        TestDBUtility.deleteAll(EqtypeTradedProductUpdqRow.TYPE);
        TestDBUtility.deleteAll(EquityCommAccountCondMstRow.TYPE);
        TestDBUtility.deleteAll(EquityCommCondRow.TYPE);
        TestDBUtility.deleteAll(EquityCommCondMstRow.TYPE);
        TestDBUtility.deleteAll(EquityCommRevMstRow.TYPE);
        TestDBUtility.deleteAll(EquityLimitPriceRangeMstRow.TYPE);
        TestDBUtility.deleteAll(EquityTickValuesMstRow.TYPE);
        TestDBUtility.deleteAll(ExchangeRateRow.TYPE);
        TestDBUtility.deleteAll(ExclusiveUseAccountRow.TYPE);
        TestDBUtility.deleteAll(ExclusiveUseAccountCondRow.TYPE);
        TestDBUtility.deleteAll(ExpAccountOpenRow.TYPE);
        TestDBUtility.deleteAll(ExtMailProcRow.TYPE);
        TestDBUtility.deleteAll(ExtMailProcTempRow.TYPE);
        TestDBUtility.deleteAll(FaqRow.TYPE);
        TestDBUtility.deleteAll(FaqNumberRow.TYPE);
        TestDBUtility.deleteAll(FeqAccountRow.TYPE);
        TestDBUtility.deleteAll(FeqBranchMarketDealtCondRow.TYPE);
        TestDBUtility.deleteAll(FeqCalendarRow.TYPE);
        TestDBUtility.deleteAll(FeqFinTransactionRow.TYPE);
        TestDBUtility.deleteAll(FeqLastClosingPriceRow.TYPE);
        TestDBUtility.deleteAll(FeqLimitPriceRangeMstRow.TYPE);
        TestDBUtility.deleteAll(FeqOrderRow.TYPE);
        TestDBUtility.deleteAll(FeqOrderexecutionEndRow.TYPE);
        TestDBUtility.deleteAll(FeqOrderActionRow.TYPE);
        TestDBUtility.deleteAll(FeqOrderChangeStatusRow.TYPE);
        TestDBUtility.deleteAll(FeqOrderEmpNumberRow.TYPE);
        TestDBUtility.deleteAll(FeqOrderExecutionRow.TYPE);
        TestDBUtility.deleteAll(FeqOrderUnitRow.TYPE);
        TestDBUtility.deleteAll(FeqProductRow.TYPE);
        TestDBUtility.deleteAll(FeqTickValuesMstRow.TYPE);
        TestDBUtility.deleteAll(FeqTradedProductRow.TYPE);
        TestDBUtility.deleteAll(FeqTradedProductUpdqRow.TYPE);
        TestDBUtility.deleteAll(FinInstitutionRow.TYPE);
        TestDBUtility.deleteAll(FinInstitutionAvailableRow.TYPE);
        TestDBUtility.deleteAll(FinInstitutionBankRow.TYPE);
        TestDBUtility.deleteAll(FixedFinTransactionRow.TYPE);
        TestDBUtility.deleteAll(ForeignCostRow.TYPE);
        TestDBUtility.deleteAll(FrgnMmfExchangeRateRow.TYPE);
        TestDBUtility.deleteAll(FxAccountRow.TYPE);
        TestDBUtility.deleteAll(FxAccountCodeRow.TYPE);
        TestDBUtility.deleteAll(FxUnnecessaryExplanationRow.TYPE);
        TestDBUtility.deleteAll(FCashBalanceRow.TYPE);
        TestDBUtility.deleteAll(FTransFinInstitutionRow.TYPE);
        TestDBUtility.deleteAll(GenCurrencyRow.TYPE);
        TestDBUtility.deleteAll(GenFinTransactionRow.TYPE);
        TestDBUtility.deleteAll(GftAccountOpenStatusRow.TYPE);
        TestDBUtility.deleteAll(GftMessageRow.TYPE);
        TestDBUtility.deleteAll(GftTransferStatusRow.TYPE);
        TestDBUtility.deleteAll(HostAccOpenAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostAccRegVoucherRow.TYPE);
        TestDBUtility.deleteAll(HostAgreeTransVoucherRow.TYPE);
        TestDBUtility.deleteAll(HostBankTransVoucherRow.TYPE);
        TestDBUtility.deleteAll(HostCashTransferRow.TYPE);
        TestDBUtility.deleteAll(HostCashTransOrderRow.TYPE);
        TestDBUtility.deleteAll(HostCashTransOrderAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostChargedInfoVoucherRow.TYPE);
        TestDBUtility.deleteAll(HostConditionRegVoucherRow.TYPE);
        TestDBUtility.deleteAll(HostContMrgVoucherRow.TYPE);
        TestDBUtility.deleteAll(HostEqtypeCloseOrderNotifyRow.TYPE);
        TestDBUtility.deleteAll(HostEqtypeOrderAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostEqtypeOrderAllRow.TYPE);
        TestDBUtility.deleteAll(HostEqtypeOrderClmdReceiptRow.TYPE);
        TestDBUtility.deleteAll(HostEqtypeOrderHistoryRow.TYPE);
        TestDBUtility.deleteAll(HostEqtypeOrderReceiptRow.TYPE);
        TestDBUtility.deleteAll(HostEqtypeSwapRow.TYPE);
        TestDBUtility.deleteAll(HostEqtypeSwapAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostEqtypeSwapReceiptRow.TYPE);
        TestDBUtility.deleteAll(HostEquityCarryoverSkipRow.TYPE);
        TestDBUtility.deleteAll(HostEquityOrderExecNotifyRow.TYPE);
        TestDBUtility.deleteAll(HostFeqChangecancelOrderRow.TYPE);
        TestDBUtility.deleteAll(HostFeqCloseOrderNotifyRow.TYPE);
        TestDBUtility.deleteAll(HostFeqOrderRow.TYPE);
        TestDBUtility.deleteAll(HostFeqOrderAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostFeqOrderExecNotifyRow.TYPE);
        TestDBUtility.deleteAll(HostForeignCashTransferRow.TYPE);
        TestDBUtility.deleteAll(HostForeignCashTransOrderRow.TYPE);
        TestDBUtility.deleteAll(HostFotypeCloseOrderNotifyRow.TYPE);
        TestDBUtility.deleteAll(HostFotypeClosingContSpecRow.TYPE);
        TestDBUtility.deleteAll(HostFotypeOrderAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostFotypeOrderAllRow.TYPE);
        TestDBUtility.deleteAll(HostFotypeOrderClmdNotifyRow.TYPE);
        TestDBUtility.deleteAll(HostFotypeOrderHistoryRow.TYPE);
        TestDBUtility.deleteAll(HostFotypeOrderReceiptRow.TYPE);
        TestDBUtility.deleteAll(HostFrgnMmfOrderRow.TYPE);
        TestDBUtility.deleteAll(HostFrgnMmfOrderAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostFCashTransOrderAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostFDepositVoucherRow.TYPE);
        TestDBUtility.deleteAll(HostGpRegVoucherRow.TYPE);
        TestDBUtility.deleteAll(HostInsiderRegVoucherRow.TYPE);
        TestDBUtility.deleteAll(HostLockRegistRow.TYPE);
        TestDBUtility.deleteAll(HostLockRegiAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostMrfAccVoucherRow.TYPE);
        TestDBUtility.deleteAll(HostMrfCancelAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostMrfOrderRow.TYPE);
        TestDBUtility.deleteAll(HostMrfOrderAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostMrfOrderCancelRow.TYPE);
        TestDBUtility.deleteAll(HostMrgsecTransferRow.TYPE);
        TestDBUtility.deleteAll(HostMrgsecTransAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostMrgsecTransNotifyRow.TYPE);
        TestDBUtility.deleteAll(HostOptionOrderExecNotifyRow.TYPE);
        TestDBUtility.deleteAll(HostOrderexecutionEndRow.TYPE);
        TestDBUtility.deleteAll(HostPaymentAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostPaymentOrderRow.TYPE);
        TestDBUtility.deleteAll(HostPostalTransVoucherRow.TYPE);
        TestDBUtility.deleteAll(HostRealnameRegVoucherRow.TYPE);
        TestDBUtility.deleteAll(HostRequestOrderNumberRow.TYPE);
        TestDBUtility.deleteAll(HostRuitoCancelAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostRuitoOrderRow.TYPE);
        TestDBUtility.deleteAll(HostRuitoOrderAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostRuitoOrderCancelRow.TYPE);
        TestDBUtility.deleteAll(HostRuitoOrderNotifyRow.TYPE);
        TestDBUtility.deleteAll(HostRuitoSellRow.TYPE);
        TestDBUtility.deleteAll(HostSecDeliveryTransferRow.TYPE);
        TestDBUtility.deleteAll(HostSellCancelRow.TYPE);
        TestDBUtility.deleteAll(HostSpsecTransNotifyRow.TYPE);
        TestDBUtility.deleteAll(HostStockholderRegVoucherRow.TYPE);
        TestDBUtility.deleteAll(HostTransferAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostTransferOrderRow.TYPE);
        TestDBUtility.deleteAll(HostTransferPaymentRow.TYPE);
        TestDBUtility.deleteAll(HostTransferReceiptRow.TYPE);
        TestDBUtility.deleteAll(HostXbmfCancelAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostXbmfOrderRow.TYPE);
        TestDBUtility.deleteAll(HostXbmfOrderAcceptRow.TYPE);
        TestDBUtility.deleteAll(HostXbmfOrderCancelRow.TYPE);
        TestDBUtility.deleteAll(HostXbmfOrderNotifyRow.TYPE);
        TestDBUtility.deleteAll(IdConfirmVoucherRow.TYPE);
        TestDBUtility.deleteAll(IfoClosingContractSpecRow.TYPE);
        TestDBUtility.deleteAll(IfoContractRow.TYPE);
        TestDBUtility.deleteAll(IfoDepositRow.TYPE);
        TestDBUtility.deleteAll(IfoFinTransactionRow.TYPE);
        TestDBUtility.deleteAll(IfoIndexMasterRow.TYPE);
        TestDBUtility.deleteAll(IfoLimitPriceRangeMasterRow.TYPE);
        TestDBUtility.deleteAll(IfoLockedContractDetailsRow.TYPE);
        TestDBUtility.deleteAll(IfoOrderRow.TYPE);
        TestDBUtility.deleteAll(IfoOrderActionRow.TYPE);
        TestDBUtility.deleteAll(IfoOrderCarryoverSkipProdRow.TYPE);
        TestDBUtility.deleteAll(IfoOrderExecutionRow.TYPE);
        TestDBUtility.deleteAll(IfoOrderExecSendMailRow.TYPE);
        TestDBUtility.deleteAll(IfoOrderUnitRow.TYPE);
        TestDBUtility.deleteAll(IfoProductRow.TYPE);
        TestDBUtility.deleteAll(IfoTickValuesMasterRow.TYPE);
        TestDBUtility.deleteAll(IfoTradedProductRow.TYPE);
        TestDBUtility.deleteAll(IfoTradedProductUpdqRow.TYPE);
        TestDBUtility.deleteAll(ImpConfirmVoucherRow.TYPE);
        TestDBUtility.deleteAll(InformationMailRequestRow.TYPE);
        TestDBUtility.deleteAll(InformCtrlItemAttributeRow.TYPE);
        TestDBUtility.deleteAll(InformCtrlItemMasterRow.TYPE);
        TestDBUtility.deleteAll(InformCtrlRequestNumberRow.TYPE);
        TestDBUtility.deleteAll(InformDivPreferencesRow.TYPE);
        TestDBUtility.deleteAll(InformDlFormMasterRow.TYPE);
        TestDBUtility.deleteAll(InsiderRow.TYPE);
        TestDBUtility.deleteAll(InstitutionRow.TYPE);
        TestDBUtility.deleteAll(InstBranchProductRow.TYPE);
        TestDBUtility.deleteAll(IpoBookbuildingRow.TYPE);
        TestDBUtility.deleteAll(IpoBookbuildingOrderActionRow.TYPE);
        TestDBUtility.deleteAll(IpoOrderRow.TYPE);
        TestDBUtility.deleteAll(IpoProductRow.TYPE);
        TestDBUtility.deleteAll(LastClosingPriceRow.TYPE);
        TestDBUtility.deleteAll(LimitPriceRangeDefsRow.TYPE);
        TestDBUtility.deleteAll(LockedAssetDetailsRow.TYPE);
        TestDBUtility.deleteAll(LoginRow.TYPE);
        TestDBUtility.deleteAll(LoginAccountManagerRow.TYPE);
        TestDBUtility.deleteAll(LoginAccountRelationRow.TYPE);
        TestDBUtility.deleteAll(LoginAttributeRow.TYPE);
        TestDBUtility.deleteAll(LoginGroupRow.TYPE);
        TestDBUtility.deleteAll(LoginGroupManagerRow.TYPE);
        TestDBUtility.deleteAll(LoginGroupMemberRow.TYPE);
        TestDBUtility.deleteAll(LoginHistoryRow.TYPE);
        TestDBUtility.deleteAll(LoginHistoryPastRow.TYPE);
        TestDBUtility.deleteAll(LoginLoginManagerRow.TYPE);
        TestDBUtility.deleteAll(LoginLoginRelationRow.TYPE);
        TestDBUtility.deleteAll(LoginPermissionRuleRow.TYPE);
        TestDBUtility.deleteAll(LoginRejectIpRow.TYPE);
        TestDBUtility.deleteAll(LoginSessionRow.TYPE);
        TestDBUtility.deleteAll(LoginSessionPropertyRow.TYPE);
        TestDBUtility.deleteAll(LoginTypeRow.TYPE);
        TestDBUtility.deleteAll(LoginTypeAttributeRow.TYPE);
        TestDBUtility.deleteAll(LoginUsernameRow.TYPE);
        TestDBUtility.deleteAll(LoginWdogAttributeRow.TYPE);
        TestDBUtility.deleteAll(MailInfoRow.TYPE);
        TestDBUtility.deleteAll(MailProcRow.TYPE);
        TestDBUtility.deleteAll(MailProcTempRow.TYPE);
        TestDBUtility.deleteAll(MainAccountRow.TYPE);
        TestDBUtility.deleteAll(MainAccountAllRow.TYPE);
        TestDBUtility.deleteAll(MarketRow.TYPE);
        TestDBUtility.deleteAll(MarketCalendarRow.TYPE);
        TestDBUtility.deleteAll(MarketMarginRatioRow.TYPE);
        TestDBUtility.deleteAll(MarketNoticeManagementRow.TYPE);
        TestDBUtility.deleteAll(MarketPreferencesRow.TYPE);
        TestDBUtility.deleteAll(MfExemptionAccountRow.TYPE);
        TestDBUtility.deleteAll(MfFixedBuyingCondRow.TYPE);
        TestDBUtility.deleteAll(MfFixedBuyingDrawAccountRow.TYPE);
        TestDBUtility.deleteAll(MfSubAssetRow.TYPE);
        TestDBUtility.deleteAll(MfTradedProductUpdqRow.TYPE);
        TestDBUtility.deleteAll(MobileOfficeInfoRegistRow.TYPE);
        TestDBUtility.deleteAll(MqMessageIdMappingsRow.TYPE);
        TestDBUtility.deleteAll(MutualFundDayBalanceRow.TYPE);
        TestDBUtility.deleteAll(MutualFundExchangeRateRow.TYPE);
        TestDBUtility.deleteAll(MutualFundFinTransactionRow.TYPE);
        TestDBUtility.deleteAll(MutualFundFrgncalRow.TYPE);
        TestDBUtility.deleteAll(MutualFundInstCommissionRow.TYPE);
        TestDBUtility.deleteAll(MutualFundInstCondSonarRow.TYPE);
        TestDBUtility.deleteAll(MutualFundOrderRow.TYPE);
        TestDBUtility.deleteAll(MutualFundOrderActionRow.TYPE);
        TestDBUtility.deleteAll(MutualFundOrderExecutionRow.TYPE);
        TestDBUtility.deleteAll(MutualFundOrderUnitRow.TYPE);
        TestDBUtility.deleteAll(MutualFundProductRow.TYPE);
        TestDBUtility.deleteAll(MutualFundProductCategoryRow.TYPE);
        TestDBUtility.deleteAll(MutualFundProductSonarRow.TYPE);
        TestDBUtility.deleteAll(MutualFundTradedProductRow.TYPE);
        TestDBUtility.deleteAll(OffFloorOrderProductRow.TYPE);
        TestDBUtility.deleteAll(OmsConOrderRequestRow.TYPE);
        TestDBUtility.deleteAll(OnlineRunStatusRow.TYPE);
        TestDBUtility.deleteAll(OrderexecutionEndRow.TYPE);
        TestDBUtility.deleteAll(OrderAcceptStatusRow.TYPE);
        TestDBUtility.deleteAll(OrderCarryoverSkipProdRow.TYPE);
        TestDBUtility.deleteAll(OrderSwitchingRow.TYPE);
        TestDBUtility.deleteAll(OrderUnitIntroduceDivRow.TYPE);
        TestDBUtility.deleteAll(OrixTpCalcResultEquityRow.TYPE);
        TestDBUtility.deleteAll(OrixTpCalcResultMarginRow.TYPE);
        TestDBUtility.deleteAll(OrixTradeBonusPlanRow.TYPE);
        TestDBUtility.deleteAll(OtherOrderExecutedCountRow.TYPE);
        TestDBUtility.deleteAll(OtherOrgOutOfSrvDateRow.TYPE);
        TestDBUtility.deleteAll(OtherOrgOutOfSrvWeekRow.TYPE);
        TestDBUtility.deleteAll(OtherOrgSrvTimeRow.TYPE);
        TestDBUtility.deleteAll(ParticipantRow.TYPE);
        TestDBUtility.deleteAll(PasswordVoucherRow.TYPE);
        TestDBUtility.deleteAll(PaymentRequisitMngRow.TYPE);
        TestDBUtility.deleteAll(PayRequiredAmountRow.TYPE);
        TestDBUtility.deleteAll(PointAdjustRow.TYPE);
        TestDBUtility.deleteAll(PointApplyRow.TYPE);
        TestDBUtility.deleteAll(PointCategoryMasterRow.TYPE);
        TestDBUtility.deleteAll(PointConvertMasterRow.TYPE);
        TestDBUtility.deleteAll(PointPremiumMasterRow.TYPE);
        TestDBUtility.deleteAll(PointTermRow.TYPE);
        TestDBUtility.deleteAll(PointTotalRow.TYPE);
        TestDBUtility.deleteAll(PointTradeDataRow.TYPE);
        TestDBUtility.deleteAll(ProcessManagementRow.TYPE);
        TestDBUtility.deleteAll(ProductRow.TYPE);
        TestDBUtility.deleteAll(ProductEstimationRatioRow.TYPE);
        TestDBUtility.deleteAll(PtsOrderexecutionEndRow.TYPE);
        TestDBUtility.deleteAll(QuestionRow.TYPE);
        TestDBUtility.deleteAll(QuestionAnswerRow.TYPE);
        TestDBUtility.deleteAll(QuoteClosingPriceRow.TYPE);
        TestDBUtility.deleteAll(RequestCodesForReadRow.TYPE);
        TestDBUtility.deleteAll(RlsAccountRow.TYPE);
        TestDBUtility.deleteAll(RlsCondOrderRow.TYPE);
        TestDBUtility.deleteAll(RlsConOrderHitNotifyRow.TYPE);
        TestDBUtility.deleteAll(RlsManualSubmitHistoryRow.TYPE);
        TestDBUtility.deleteAll(RlsOmsOrderRow.TYPE);
        TestDBUtility.deleteAll(RlsOrderMissRow.TYPE);
        TestDBUtility.deleteAll(RlsPriceCondRow.TYPE);
        TestDBUtility.deleteAll(RsvEqClosingContractSpecRow.TYPE);
        TestDBUtility.deleteAll(RsvEqOrderActionRow.TYPE);
        TestDBUtility.deleteAll(RsvEqOrderUnitRow.TYPE);
        TestDBUtility.deleteAll(RsvIfoClosingContractSpecRow.TYPE);
        TestDBUtility.deleteAll(RsvIfoOrderActionRow.TYPE);
        TestDBUtility.deleteAll(RsvIfoOrderUnitRow.TYPE);
        TestDBUtility.deleteAll(RuitoFinTransactionRow.TYPE);
        TestDBUtility.deleteAll(RuitoOrderRow.TYPE);
        TestDBUtility.deleteAll(RuitoOrderActionRow.TYPE);
        TestDBUtility.deleteAll(RuitoOrderExecutionRow.TYPE);
        TestDBUtility.deleteAll(RuitoOrderUnitRow.TYPE);
        TestDBUtility.deleteAll(RuitoProductRow.TYPE);
        TestDBUtility.deleteAll(RuitoTradedProductRow.TYPE);
        TestDBUtility.deleteAll(RuitoTradedProductUpdqRow.TYPE);
        TestDBUtility.deleteAll(SecurityCashoutRestraintRow.TYPE);
        TestDBUtility.deleteAll(SecurityProductRow.TYPE);
        TestDBUtility.deleteAll(SecurityShortageAccountRow.TYPE);
        TestDBUtility.deleteAll(SecurityShortageAccountHistRow.TYPE);
        TestDBUtility.deleteAll(SecReceiptDeliveryActionRow.TYPE);
        TestDBUtility.deleteAll(SegmentUrlRow.TYPE);
        TestDBUtility.deleteAll(ShortSellingRestraintTimeRow.TYPE);
        TestDBUtility.deleteAll(SoapConnectPrefMsgRow.TYPE);
        TestDBUtility.deleteAll(SoapConnectPrefRpcRow.TYPE);
        TestDBUtility.deleteAll(SoapMessageRow.TYPE);
        TestDBUtility.deleteAll(SonarTraderRow.TYPE);
        TestDBUtility.deleteAll(SrvRegiApplicationRow.TYPE);
        TestDBUtility.deleteAll(SsoMessageRow.TYPE);
        TestDBUtility.deleteAll(StockOptionProductRow.TYPE);
        TestDBUtility.deleteAll(StockSecuredLoanRow.TYPE);
        TestDBUtility.deleteAll(SubAccountRow.TYPE);
        TestDBUtility.deleteAll(SubAccountPreferencesRow.TYPE);
        TestDBUtility.deleteAll(SystemPreferencesRow.TYPE);
        TestDBUtility.deleteAll(TaxRateTableRow.TYPE);
        TestDBUtility.deleteAll(TickValuesDefsRow.TYPE);
        TestDBUtility.deleteAll(TpAssetHistoryRow.TYPE);
        TestDBUtility.deleteAll(TpCalcResultEquityRow.TYPE);
        TestDBUtility.deleteAll(TpCalcResultEquityDetailRow.TYPE);
        TestDBUtility.deleteAll(TpCalcResultExecNotifyRow.TYPE);
        TestDBUtility.deleteAll(TpCalcResultMarginRow.TYPE);
        TestDBUtility.deleteAll(TpCalcResultMarginDetailRow.TYPE);
        TestDBUtility.deleteAll(TpCashBalanceRow.TYPE);
        TestDBUtility.deleteAll(TpCashBalanceFrgnRow.TYPE);
        TestDBUtility.deleteAll(TpOtherTempRestraintRow.TYPE);
        TestDBUtility.deleteAll(TradedProductRow.TYPE);
        TestDBUtility.deleteAll(TradedProductCalendarRow.TYPE);
        TestDBUtility.deleteAll(TradedProductUpdqRow.TYPE);
        TestDBUtility.deleteAll(TraderRow.TYPE);
        TestDBUtility.deleteAll(TraderAccountInfoRow.TYPE);
        TestDBUtility.deleteAll(TradeConditionVoucherRow.TYPE);
        TestDBUtility.deleteAll(TradingpowerCalcConditionRow.TYPE);
        TestDBUtility.deleteAll(TradingTimeRow.TYPE);
        TestDBUtility.deleteAll(TransferedFinInstitutionRow.TYPE);
        TestDBUtility.deleteAll(TriggerOrderStopRow.TYPE);
        TestDBUtility.deleteAll(UwgAccountOpenStatusRow.TYPE);
        TestDBUtility.deleteAll(UwgTransferStatusRow.TYPE);
        TestDBUtility.deleteAll(VariousInformRow.TYPE);
        TestDBUtility.deleteAll(VirtualServerChangeRow.TYPE);
        TestDBUtility.deleteAll(VirtualServerInformationRow.TYPE);
        TestDBUtility.deleteAll(Web3QuoteProtoRow.TYPE);
        TestDBUtility.deleteAll(YellowCustomerRow.TYPE);
        TestDBUtility.deleteAll(YCustomerRow.TYPE);
    }
}
@
