DROP VIEW RLS_OMS_ORDER_EX CASCADE CONSTRAINTS;
DROP VIEW RLS_OMS_ORDER_EXEC_QTY CASCADE CONSTRAINTS;
DROP VIEW RLS_COND_ORD_HUMAN CASCADE CONSTRAINTS;


DROP TABLE RLS_MARKET_RSP CASCADE CONSTRAINTS;
DROP TABLE RLS_CHAIN_COND CASCADE CONSTRAINTS;
DROP TABLE RLS_TIME_COND CASCADE CONSTRAINTS;
DROP TABLE RLS_TICKER CASCADE CONSTRAINTS;
DROP TABLE RLS_PRICE_COND CASCADE CONSTRAINTS;
DROP TABLE RLS_OMS_ORDER_GEN CASCADE CONSTRAINTS;
DROP TABLE RLS_OMS_ORDER CASCADE CONSTRAINTS;
DROP TABLE RLS_COND_ORDER_HIST CASCADE CONSTRAINTS;
DROP TABLE RLS_COND_ORDER CASCADE CONSTRAINTS;
DROP TABLE RLS_ACCOUNT CASCADE CONSTRAINTS;

DROP SEQUENCE RLS_COND_ORDER_HISTORY_ID_SEQ;
DROP SEQUENCE RLS_COND_ORDER_ID_SEQ;
DROP SEQUENCE RLS_COND_ORDER_OP_SEQ;
DROP SEQUENCE RLS_COND_ORDER_SEQ;
DROP SEQUENCE RLS_EVENT_SEQ;
DROP SEQUENCE RLS_MARKET_RSP_SEQ;
DROP SEQUENCE RLS_OMS_ORDER_ID_SEQ;
DROP SEQUENCE RLS_OMS_ORDER_SEQ;
