head	1.1;
access;
symbols;
locks; strict;
comment	@// @;


1.1
date	2011.03.15.03.05.17;	author zhang-tengyu;	state Exp;
branches;
next	;
deltatype	text;
kopt	kv;
permissions	666;
commitid	8b84d7ecf833551;
filename	WebServiceSoap_Stub.java;


desc
@@


1.1
log
@*** empty log message ***
@
text
@package fx.client;
/**
 * Generated class, do not edit.
 *
 * This stub class was generated by weblogic
 * webservice stub gen on Tue Jul 29 13:33:51 JST 2008 */

public class WebServiceSoap_Stub 
     extends weblogic.webservice.core.rpc.StubImpl 
     implements  fx.client.WebServiceSoap{

  public WebServiceSoap_Stub( weblogic.webservice.Port _port ){
    super( _port, fx.client.WebServiceSoap.class );
  }

  /**
   * EntryOshirase 
   */

  public jp.co.hitachi.www.TFX.WebService.EntryOshiraseResponse entryOshirase(jp.co.hitachi.www.TFX.WebService.EntryOshirase parameters) 
       throws java.rmi.RemoteException {

    java.util.HashMap _args = new java.util.HashMap();
    _args.put( "parameters", _wrap( parameters ) );
           try{
      java.lang.Object _result = _invoke( "EntryOshirase", _args );
      return (jp.co.hitachi.www.TFX.WebService.EntryOshiraseResponse)_result;
        } catch (javax.xml.rpc.JAXRPCException e) {
      throw new java.rmi.RemoteException( e.getMessage(), e.getLinkedCause() );
    } catch (javax.xml.rpc.soap.SOAPFaultException e) {
      throw new java.rmi.RemoteException( "SOAP Fault:" + e + "\nDetail:\n"+e.getDetail(), e );
    } catch (java.lang.Throwable e) {
      throw new java.rmi.RemoteException( e.getMessage(), e );    }
  }
  /**
   * Convenience method for EntryOshirase 
   */

  public jp.co.hitachi.www.TFX.WebService.EntryOshiraseOut entryOshirase(jp.co.hitachi.www.TFX.WebService.EntryOshiraseIn in0)
       throws java.rmi.RemoteException {

    jp.co.hitachi.www.TFX.WebService.EntryOshirase _input = 
         new jp.co.hitachi.www.TFX.WebService.EntryOshirase();

        _input.setIn0( in0 );
      
    jp.co.hitachi.www.TFX.WebService.EntryOshiraseResponse _result = entryOshirase( _input );

        return _result.getEntryOshiraseReturn();
      }
  /**
   * DeleteOshirase 
   */

  public jp.co.hitachi.www.TFX.WebService.DeleteOshiraseResponse deleteOshirase(jp.co.hitachi.www.TFX.WebService.DeleteOshirase parameters) 
       throws java.rmi.RemoteException {

    java.util.HashMap _args = new java.util.HashMap();
    _args.put( "parameters", _wrap( parameters ) );
           try{
      java.lang.Object _result = _invoke( "DeleteOshirase", _args );
      return (jp.co.hitachi.www.TFX.WebService.DeleteOshiraseResponse)_result;
        } catch (javax.xml.rpc.JAXRPCException e) {
      throw new java.rmi.RemoteException( e.getMessage(), e.getLinkedCause() );
    } catch (javax.xml.rpc.soap.SOAPFaultException e) {
      throw new java.rmi.RemoteException( "SOAP Fault:" + e + "\nDetail:\n"+e.getDetail(), e );
    } catch (java.lang.Throwable e) {
      throw new java.rmi.RemoteException( e.getMessage(), e );    }
  }
  /**
   * Convenience method for DeleteOshirase 
   */

  public jp.co.hitachi.www.TFX.WebService.DeleteOshiraseOut deleteOshirase(jp.co.hitachi.www.TFX.WebService.DeleteOshiraseIn in0)
       throws java.rmi.RemoteException {

    jp.co.hitachi.www.TFX.WebService.DeleteOshirase _input = 
         new jp.co.hitachi.www.TFX.WebService.DeleteOshirase();

        _input.setIn0( in0 );
      
    jp.co.hitachi.www.TFX.WebService.DeleteOshiraseResponse _result = deleteOshirase( _input );

        return _result.getDeleteOshiraseReturn();
      }
  /**
   * ChangeRiyousya 
   */

  public jp.co.hitachi.www.TFX.WebService.ChangeRiyousyaResponse changeRiyousya(jp.co.hitachi.www.TFX.WebService.ChangeRiyousya parameters) 
       throws java.rmi.RemoteException {

    java.util.HashMap _args = new java.util.HashMap();
    _args.put( "parameters", _wrap( parameters ) );
           try{
      java.lang.Object _result = _invoke( "ChangeRiyousya", _args );
      return (jp.co.hitachi.www.TFX.WebService.ChangeRiyousyaResponse)_result;
        } catch (javax.xml.rpc.JAXRPCException e) {
      throw new java.rmi.RemoteException( e.getMessage(), e.getLinkedCause() );
    } catch (javax.xml.rpc.soap.SOAPFaultException e) {
      throw new java.rmi.RemoteException( "SOAP Fault:" + e + "\nDetail:\n"+e.getDetail(), e );
    } catch (java.lang.Throwable e) {
      throw new java.rmi.RemoteException( e.getMessage(), e );    }
  }
  /**
   * Convenience method for ChangeRiyousya 
   */

  public jp.co.hitachi.www.TFX.WebService.ChangeRiyousyaOut changeRiyousya(jp.co.hitachi.www.TFX.WebService.ChangeRiyousyaIn in0)
       throws java.rmi.RemoteException {

    jp.co.hitachi.www.TFX.WebService.ChangeRiyousya _input = 
         new jp.co.hitachi.www.TFX.WebService.ChangeRiyousya();

        _input.setIn0( in0 );
      
    jp.co.hitachi.www.TFX.WebService.ChangeRiyousyaResponse _result = changeRiyousya( _input );

        return _result.getChangeRiyousyaReturn();
      }
  /**
   * InquirySyoriKekka 
   */

  public jp.co.hitachi.www.TFX.WebService.InquirySyoriKekkaResponse inquirySyoriKekka(jp.co.hitachi.www.TFX.WebService.InquirySyoriKekka parameters) 
       throws java.rmi.RemoteException {

    java.util.HashMap _args = new java.util.HashMap();
    _args.put( "parameters", _wrap( parameters ) );
           try{
      java.lang.Object _result = _invoke( "InquirySyoriKekka", _args );
      return (jp.co.hitachi.www.TFX.WebService.InquirySyoriKekkaResponse)_result;
        } catch (javax.xml.rpc.JAXRPCException e) {
      throw new java.rmi.RemoteException( e.getMessage(), e.getLinkedCause() );
    } catch (javax.xml.rpc.soap.SOAPFaultException e) {
      throw new java.rmi.RemoteException( "SOAP Fault:" + e + "\nDetail:\n"+e.getDetail(), e );
    } catch (java.lang.Throwable e) {
      throw new java.rmi.RemoteException( e.getMessage(), e );    }
  }
  /**
   * Convenience method for InquirySyoriKekka 
   */

  public jp.co.hitachi.www.TFX.WebService.InquirySyoriKekkaOut inquirySyoriKekka(jp.co.hitachi.www.TFX.WebService.InquirySyoriKekkaIn in0)
       throws java.rmi.RemoteException {

    jp.co.hitachi.www.TFX.WebService.InquirySyoriKekka _input = 
         new jp.co.hitachi.www.TFX.WebService.InquirySyoriKekka();

        _input.setIn0( in0 );
      
    jp.co.hitachi.www.TFX.WebService.InquirySyoriKekkaResponse _result = inquirySyoriKekka( _input );

        return _result.getInquirySyoriKekkaReturn();
      }
  /**
   * EntryRiyousya 
   */

  public jp.co.hitachi.www.TFX.WebService.EntryRiyousyaResponse entryRiyousya(jp.co.hitachi.www.TFX.WebService.EntryRiyousya parameters) 
       throws java.rmi.RemoteException {

    java.util.HashMap _args = new java.util.HashMap();
    _args.put( "parameters", _wrap( parameters ) );
           try{
      java.lang.Object _result = _invoke( "EntryRiyousya", _args );
      return (jp.co.hitachi.www.TFX.WebService.EntryRiyousyaResponse)_result;
        } catch (javax.xml.rpc.JAXRPCException e) {
      throw new java.rmi.RemoteException( e.getMessage(), e.getLinkedCause() );
    } catch (javax.xml.rpc.soap.SOAPFaultException e) {
      throw new java.rmi.RemoteException( "SOAP Fault:" + e + "\nDetail:\n"+e.getDetail(), e );
    } catch (java.lang.Throwable e) {
      throw new java.rmi.RemoteException( e.getMessage(), e );    }
  }
  /**
   * Convenience method for EntryRiyousya 
   */

  public jp.co.hitachi.www.TFX.WebService.EntryRiyousyaOut entryRiyousya(jp.co.hitachi.www.TFX.WebService.EntryRiyousyaIn in0)
       throws java.rmi.RemoteException {

    jp.co.hitachi.www.TFX.WebService.EntryRiyousya _input = 
         new jp.co.hitachi.www.TFX.WebService.EntryRiyousya();

        _input.setIn0( in0 );
      
    jp.co.hitachi.www.TFX.WebService.EntryRiyousyaResponse _result = entryRiyousya( _input );

        return _result.getEntryRiyousyaReturn();
      }
  /**
   * EntryReceipt 
   */

  public jp.co.hitachi.www.TFX.WebService.EntryReceiptResponse entryReceipt(jp.co.hitachi.www.TFX.WebService.EntryReceipt parameters) 
       throws java.rmi.RemoteException {

    java.util.HashMap _args = new java.util.HashMap();
    _args.put( "parameters", _wrap( parameters ) );
           try{
      java.lang.Object _result = _invoke( "EntryReceipt", _args );
      return (jp.co.hitachi.www.TFX.WebService.EntryReceiptResponse)_result;
        } catch (javax.xml.rpc.JAXRPCException e) {
      throw new java.rmi.RemoteException( e.getMessage(), e.getLinkedCause() );
    } catch (javax.xml.rpc.soap.SOAPFaultException e) {
      throw new java.rmi.RemoteException( "SOAP Fault:" + e + "\nDetail:\n"+e.getDetail(), e );
    } catch (java.lang.Throwable e) {
      throw new java.rmi.RemoteException( e.getMessage(), e );    }
  }
  /**
   * Convenience method for EntryReceipt 
   */

  public jp.co.hitachi.www.TFX.WebService.EntryReceiptOut entryReceipt(jp.co.hitachi.www.TFX.WebService.EntryReceiptIn in0)
       throws java.rmi.RemoteException {

    jp.co.hitachi.www.TFX.WebService.EntryReceipt _input = 
         new jp.co.hitachi.www.TFX.WebService.EntryReceipt();

        _input.setIn0( in0 );
      
    jp.co.hitachi.www.TFX.WebService.EntryReceiptResponse _result = entryReceipt( _input );

        return _result.getEntryReceiptReturn();
      }
}@
