head	1.1;
access;
symbols;
locks; strict;
comment	@// @;


1.1
date	2011.03.15.03.05.09;	author zhang-tengyu;	state Exp;
branches;
next	;
deltatype	text;
kopt	kv;
permissions	666;
commitid	8b84d7ecf833551;
filename	WebService.java;


desc
@@


1.1
log
@*** empty log message ***
@
text
@package fx.client;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Tue Jul 29 13:33:51 JST 2008 */

public interface WebService extends javax.xml.rpc.Service{

  weblogic.webservice.context.WebServiceContext context();

  weblogic.webservice.context.WebServiceContext joinContext() 
       throws weblogic.webservice.context.ContextNotFoundException;

  fx.client.WebServiceSoap getWebServiceSoap(String port_str) throws javax.xml.rpc.ServiceException;

  fx.client.WebServiceSoap getWebServiceSoap(String username, String password, String port_str) throws javax.xml.rpc.ServiceException;

}@
