head	1.1;
access;
symbols;
locks; strict;
comment	@// @;


1.1
date	2011.03.15.03.05.01;	author zhang-tengyu;	state Exp;
branches;
next	;
deltatype	text;
kopt	kv;
permissions	666;
commitid	8b84d7ecf833551;
filename	WebService_Impl.java;


desc
@@


1.1
log
@*** empty log message ***
@
text
@package fx.client;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Tue Jul 29 13:33:51 JST 2008 */

public class WebService_Impl 
     extends weblogic.webservice.core.rpc.ServiceImpl 
     implements fx.client.WebService{

  public WebService_Impl() 
       throws java.io.IOException{

    this( "fx/client/WebService.wsdl" );
  }

  public WebService_Impl( String wsdlurl ) 
       throws java.io.IOException{

    super( wsdlurl, "fx.client.WebService" );
  }
    //***********************************
  // Port Name: WebService 
  // Port Type: WebServiceSoap  //***********************************

  fx.client.WebServiceSoap mvar_WebService;


  /**
   * returns a port in this service 
   *
   */

//  public fx.client.WebServiceSoap getWebServiceSoap(){
//
//    if( mvar_WebService == null ){
//      mvar_WebService = 
//        new fx.client.WebServiceSoap_Stub( _getPort( "WebService" ) );
//    }
//
//    return mvar_WebService;
//
//  }
//
//public fx.client.WebServiceSoap getWebServiceSoap(String username, String password){
//
//    _setUser( username, password, getWebServiceSoap() );
//
//    return getWebServiceSoap();
//  }

  public fx.client.WebServiceSoap getWebServiceSoap(String port_str){

    if( mvar_WebService == null ){
      mvar_WebService = 
        new fx.client.WebServiceSoap_Stub( _getPort( port_str ) );
    }

    return mvar_WebService;

  }
  
  public fx.client.WebServiceSoap getWebServiceSoap(String username, String password, String port_str){

    _setUser( username, password, getWebServiceSoap(port_str) );

    return getWebServiceSoap(port_str);
  }
}@
