head	1.1;
access;
symbols;
locks; strict;
comment	@// @;


1.1
date	2011.03.15.03.05.42;	author zhang-tengyu;	state Exp;
branches;
next	;
deltatype	text;
kopt	kv;
permissions	666;
commitid	8b84d7ecf833551;
filename	AdministrativeAPI.java;


desc
@@


1.1
log
@*** empty log message ***
@
text
@package esupport.client;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Thu Oct 30 17:29:00 JST 2008 */

public interface AdministrativeAPI extends javax.xml.rpc.Service{

  weblogic.webservice.context.WebServiceContext context();

  weblogic.webservice.context.WebServiceContext joinContext() 
       throws weblogic.webservice.context.ContextNotFoundException;

  esupport.client.AdministrativeAPIPort getAdministrativeAPIPort12() throws javax.xml.rpc.ServiceException;

  esupport.client.AdministrativeAPIPort getAdministrativeAPIPort12(String username, String password) throws javax.xml.rpc.ServiceException;

  esupport.client.AdministrativeAPIPort getAdministrativeAPIPort(String port_str) throws javax.xml.rpc.ServiceException;

  esupport.client.AdministrativeAPIPort getAdministrativeAPIPort(String username, String password, String port_str) throws javax.xml.rpc.ServiceException;

}@
