head	1.1;
access;
symbols;
locks; strict;
comment	@// @;


1.1
date	2011.03.15.03.05.51;	author zhang-tengyu;	state Exp;
branches;
next	;
deltatype	text;
kopt	kv;
permissions	666;
commitid	8b84d7ecf833551;
filename	AdministrativeAPIPort.java;


desc
@@


1.1
log
@*** empty log message ***
@
text
@package esupport.client;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Thu Oct 30 17:29:00 JST 2008 */

public interface AdministrativeAPIPort extends java.rmi.Remote{

  /**
   * sendSyncRequest 
   */

  public com.gftforex.soap.api.SendSyncRequestResponse sendSyncRequest(com.gftforex.soap.api.SendSyncRequest parameters) 
       throws esupport.client.AuthorizationFailedException, esupport.client.InternalErrorException, java.rmi.RemoteException ;
  /**
   * getResponse 
   */

  public com.gftforex.soap.api.ResultInfoBase[] getResponse(com.gftforex.soap.api.GetResponse parameters) 
       throws esupport.client.AuthorizationFailedException, esupport.client.InternalErrorException, java.rmi.RemoteException ;
  /**
   * sendRequest 
   */

  public com.gftforex.soap.api.SendRequestResponse sendRequest(com.gftforex.soap.api.SendRequest parameters) 
       throws esupport.client.AuthorizationFailedException, esupport.client.InternalErrorException, java.rmi.RemoteException ;
  /**
   * getResponseByCommandId 
   */

  public com.gftforex.soap.api.GetResponseByCommandIdResponse getResponseByCommandId(com.gftforex.soap.api.GetResponseByCommandId parameters) 
       throws esupport.client.AuthorizationFailedException, esupport.client.InternalErrorException, java.rmi.RemoteException ;
  /**
   * Convenience method for getResponseByCommandId 
   */

  public com.gftforex.soap.api.ResultInfoBase getResponseByCommandId(java.lang.String commandId, com.gftforex.soap.api.AuthToken authToken)
       throws esupport.client.AuthorizationFailedException, esupport.client.InternalErrorException, java.rmi.RemoteException ;
  /**
   * isOk 
   */

  public com.gftforex.soap.api.IsOkResponse isOk(com.gftforex.soap.api.IsOk parameters) 
       throws java.rmi.RemoteException ;
  /**
   * Convenience method for isOk 
   */

  public boolean isOk()
       throws java.rmi.RemoteException ;
}@
