head	1.1;
access;
symbols;
locks; strict;
comment	@// @;


1.1
date	2011.03.15.03.05.38;	author zhang-tengyu;	state Exp;
branches;
next	;
deltatype	text;
kopt	kv;
permissions	666;
commitid	8b84d7ecf833551;
filename	AdministrativeAPI_Impl.java;


desc
@@


1.1
log
@*** empty log message ***
@
text
@package esupport.client;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Thu Oct 30 17:29:00 JST 2008 */

public class AdministrativeAPI_Impl 
     extends weblogic.webservice.core.rpc.ServiceImpl 
     implements esupport.client.AdministrativeAPI{

  public AdministrativeAPI_Impl() 
       throws java.io.IOException{

    this( "esupport/client/AdministrativeAPI.wsdl" );
  }

  public AdministrativeAPI_Impl( String wsdlurl ) 
       throws java.io.IOException{

    super( wsdlurl, "esupport.client.AdministrativeAPI" );
  }
    //***********************************
  // Port Name: AdministrativeAPIPort12 
  // Port Type: AdministrativeAPIPort  //***********************************

  esupport.client.AdministrativeAPIPort mvar_AdministrativeAPIPort12;


  /**
   * returns a port in this service 
   *
   */

  public esupport.client.AdministrativeAPIPort getAdministrativeAPIPort12(){

    if( mvar_AdministrativeAPIPort12 == null ){
      mvar_AdministrativeAPIPort12 = 
        new esupport.client.AdministrativeAPIPort_Stub( _getPort( "AdministrativeAPIPort12" ) );
    }

    return mvar_AdministrativeAPIPort12;

  }

  public esupport.client.AdministrativeAPIPort getAdministrativeAPIPort12(String username, String password){

    _setUser( username, password, getAdministrativeAPIPort12() );

    return getAdministrativeAPIPort12();
  }    //***********************************
  // Port Name: AdministrativeAPIPort 
  // Port Type: AdministrativeAPIPort  //***********************************

  esupport.client.AdministrativeAPIPort mvar_AdministrativeAPIPort;


  /**
   * returns a port in this service 
   *
   */

  public esupport.client.AdministrativeAPIPort getAdministrativeAPIPort(String port_str){

    if( mvar_AdministrativeAPIPort == null ){
      mvar_AdministrativeAPIPort = 
        new esupport.client.AdministrativeAPIPort_Stub( _getPort( port_str ) );
    }

    return mvar_AdministrativeAPIPort;

  }

  public esupport.client.AdministrativeAPIPort getAdministrativeAPIPort(String username, String password, String port_str){

    _setUser( username, password, getAdministrativeAPIPort(port_str) );

    return getAdministrativeAPIPort(port_str);
  }
}@
