head	1.1;
access;
symbols;
locks; strict;
comment	@// @;


1.1
date	2011.03.15.03.05.47;	author zhang-tengyu;	state Exp;
branches;
next	;
deltatype	text;
kopt	kv;
permissions	666;
commitid	8b84d7ecf833551;
filename	InternalErrorException.java;


desc
@@


1.1
log
@*** empty log message ***
@
text
@package esupport.client;

/**
 * Generated class, do not edit.
 *
 * This exception class was generated by weblogic
 * webservice exception gen on Thu Oct 30 17:29:00 JST 2008 */

public class InternalErrorException     extends java.lang.Exception
     implements java.io.Serializable 
{

  private java.lang.String info;

  public InternalErrorException(java.lang.String t) {
    info = t;
  }

  public java.lang.String getMsg() {
    return info;
  }

  public void setMsg(java.lang.String t) {
    info = t;
  }
}@
